baseURL = ""

canonifyurls = true
DefaultContentLanguage = "current"
languageCode = "en-us"
relativeURLs = true

title = "amcheck/amcheck_next: functions for verifying PostgreSQL relation integrity"
theme = "crunchy-hugo-theme"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"
publishDir = ""

defaultContentLanguage = "current"
defaultContentLanguageInSubdir= true
enableMissingTranslationPlaceholders = true

[Languages]
[Languages.current]
title = "amcheck/amcheck_next: functions for verifying PostgreSQL relation integrity"
weight = 1
languageName = "current"

[params]
showVisitedLinks = false # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> <label>Source</label>"
url = "https://github.com/petergeoghegan/amcheck"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-file-contract'></i> <label>License</label>"
url = "https://github.com/petergeoghegan/amcheck/blob/master/LICENSE.md"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-copy'></i> <label>View All Documentation</label>"
url = "https://access.crunchydata.com/documentation"
weight = 30

[[menu.downloads]]
name = "<i class='fas fa-file-pdf'></i> <label>PDF</label>"
url = "/pdf/amcheck_next.pdf"
weight = 20

#[[menu.downloads]]
#name = "<i class='fas fa-book'></i> <label>EPUB</label>"
#url = "/pdf/amcheck_next.epub"
#weight = 30
